#!/bin/bash
# scripts/2_instance/train_chatbot.sh
# ================================================
# Chatbot Training Script (2 User Simulator Instances)
# GPU Allocation:
#    - Chatbot Training: GPU 0,1,2,3 (4 cards)
#    - User Sim 1:   GPU 6 (1 card, port 5000)
#    - User Sim 2:   GPU 7 (1 card, port 5001)
# ================================================

set -e

chatbot_model_path=$1
client_model_path=$2
model_name=$3
step=$4
training_steps=${5:-10}
keep_vllm_alive=${6:-false}

if [ -z "$chatbot_model_path" ] || [ -z "$client_model_path" ] || [ -z "$model_name" ] || [ -z "$step" ]; then
    echo "❌ Error: Missing required parameters"
    echo "Usage: bash $0 <chatbot_model_path> <client_model_path> <model_name> <step> [training_steps] [keep_vllm_alive]"
    exit 1
fi

RUN_ID=$(date +%s%N)
export RUN_ID
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

# ✅ Read configuration from environment variables (if set by main.sh), otherwise use default values
TRAIN_BATCH_SIZE=${TRAIN_BATCH_SIZE:-60}
VAL_BATCH_SIZE=${VAL_BATCH_SIZE:-60}
TEST_FREQ=${TEST_FREQ:-1}
WAND_PROJECT=${WAND_PROJECT:-sead_chatbot}
EXPERIMENT_NAME=${EXPERIMENT_NAME:-2ins_training}

# ✅ 2 Instance Config
USER_SIM_PORTS=(5000 5001)
USER_SIM_GPUS=("6" "7")
CHATBOT_GPUS="0,1,2,3,4,5"
CHATBOT_N_GPUS=6
CHATBOT_URLS="http://localhost:5000,http://localhost:5001"

echo "=========================================="
echo "📋 Training Parameters (2 User Sim Instances)"
echo "=========================================="
echo "  Chatbot Model: $chatbot_model_path"
echo "  Client Model: $client_model_path"
echo "  Output Name: $model_name"
echo "  Iteration Step: $step"
echo "  Training Steps: $training_steps"
echo "  Train Batch Size: $TRAIN_BATCH_SIZE"
echo "  Validation Batch Size: $VAL_BATCH_SIZE"
echo "  Test Frequency: Every $TEST_FREQ steps"
echo "  Keep vLLM Running: $keep_vllm_alive"
echo "  Chatbot GPUs: $CHATBOT_GPUS ($CHATBOT_N_GPUS cards)"
echo "  User Sim URLs: $CHATBOT_URLS"
echo "=========================================="
echo ""

# ✅ Check if vLLM Servers are already running
echo "🔍 Checking vLLM Server status..."
ALL_RUNNING=true

for port in "${USER_SIM_PORTS[@]}"; do
    if curl -s -f "http://localhost:${port}/health" > /dev/null 2>&1; then
        echo "✅ vLLM Server on port $port is already running"
    else
        echo "⚠️  vLLM Server on port $port is NOT running"
        ALL_RUNNING=false
    fi
done

if [ "$ALL_RUNNING" = false ]; then
    echo ""
    echo "🚀 Need to start vLLM Servers..."

    # Clean up existing services
    echo "🧹 Cleaning up existing vLLM services..."
    pkill -9 -f "vllm_server" 2>/dev/null || true
    sleep 2

    source your/path/to/conda/etc/profile.d/conda.sh  # TODO: Replace with your conda path
    conda activate your/path/to/conda/envs/verl_wcz  # TODO: Replace with your vLLM server conda environment path

    for i in 0 1; do
        port="${USER_SIM_PORTS[$i]}"
        gpu_ids="${USER_SIM_GPUS[$i]}"
        sim_run_id="${RUN_ID}_sim${i}"

        echo ""
        echo "🚀 Starting vLLM Server $((i+1)) (User Role-play Model, GPU $gpu_ids, Port $port)..."
        bash ./SEAD/vllm_service/start_vllm.sh "$client_model_path" "$sim_run_id" "$step" "call_client" "$port" "$gpu_ids"

        echo ""
        echo "⏳ Waiting for vLLM Server on port $port to start..."
        MAX_WAIT=99999
        WAIT_COUNT=0

        while [ $WAIT_COUNT -lt $MAX_WAIT ]; do
            if curl -s -f "http://localhost:${port}/health" > /dev/null 2>&1; then
                echo "✅ vLLM Server on port $port is ready!"
                break
            fi

            echo "   Waiting... (${WAIT_COUNT}s / ${MAX_WAIT}s)"
            sleep 5
            WAIT_COUNT=$((WAIT_COUNT + 5))
        done

        if [ $WAIT_COUNT -ge $MAX_WAIT ]; then
            echo ""
            echo "❌ Error: vLLM Server startup timeout on port $port"
            tail -100 "./outputs/logs/vllm_server/call_client_server_step${step}_port${port}.log"
            exit 1
        fi
    done

    echo ""
    echo "✅ All vLLM Servers are ready!"
fi

echo ""
echo "🔄 Switching to training environment..."
conda activate your/path/to/conda/envs/vllm063torch240cu121py310  # TODO: Replace with your training conda environment path

export CUDA_VISIBLE_DEVICES=$CHATBOT_GPUS
export VLLM_ATTENTION_BACKEND=XFORMERS
export VLLM_MODEL_PATH="$client_model_path"
export VLLM_GPU_IDS="${USER_SIM_GPUS[0]}"  # For restart: use first sim's GPUs as default

# ✅ Validate training data (generated by main.sh)
echo ""
echo "🔍 Validating training data..."

WORK_DIR=$(pwd)
TRAIN_DATA="${WORK_DIR}/outputs/prompt_data/train_chatbot.parquet"
VAL_DATA="${WORK_DIR}/outputs/prompt_data/test_chatbot.parquet"

if [ ! -f "$TRAIN_DATA" ]; then
    echo "❌ Error: Training data does not exist: $TRAIN_DATA"
    echo "   Data should be generated by main.sh"
    exit 1
fi

if [ ! -f "$VAL_DATA" ]; then
    echo "❌ Error: Validation data does not exist: $VAL_DATA"
    echo "   Data should be generated by main.sh"
    exit 1
fi

echo "✅ Data files exist"

# ✅ Validate data volume
python3 << EOF
import pandas as pd
import sys

try:
    train_df = pd.read_parquet('$TRAIN_DATA')
    val_df = pd.read_parquet('$VAL_DATA')

    print(f"✅ Training set: {len(train_df)} rows")
    print(f"✅ Validation set: {len(val_df)} rows")

    if len(train_df) == 0:
        print("❌ Training set is empty")
        sys.exit(1)

    if len(val_df) == 0:
        print("❌ Validation set is empty")
        sys.exit(1)

    # Check if data volume is sufficient
    if len(train_df) < $TRAIN_BATCH_SIZE:
        print(f"❌ Error: Training set too small ({len(train_df)} < $TRAIN_BATCH_SIZE)")
        sys.exit(1)

    if len(val_df) < $VAL_BATCH_SIZE:
        print(f"❌ Error: Validation set too small ({len(val_df)} < $VAL_BATCH_SIZE)")
        sys.exit(1)

    print("✅ Data volume is sufficient")

except Exception as e:
    print(f"❌ Data validation failed: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)
EOF

if [ $? -ne 0 ]; then
    echo "❌ Data validation failed"
    exit 1
fi

# ✅ Validate user_params files
echo ""
echo "📊 Validating user_params files:"
if [ -f "./outputs/temp/train_client_prompts.jsonl" ]; then
    ACTUAL_TRAIN=$(wc -l < ./outputs/temp/train_client_prompts.jsonl)
    echo "   train_client_prompts.jsonl: ${ACTUAL_TRAIN} entries"
else
    echo "   ⚠️  train_client_prompts.jsonl not found"
fi

if [ -f "./outputs/temp/test_client_prompts.jsonl" ]; then
    ACTUAL_TEST=$(wc -l < ./outputs/temp/test_client_prompts.jsonl)
    echo "   test_client_prompts.jsonl: ${ACTUAL_TEST} entries"
else
    echo "   ⚠️  test_client_prompts.jsonl not found"
fi

# ✅ Reset indices
echo ""
echo "🔄 Resetting indices..."
echo "0" > ./outputs/temp/train_index.txt
echo "0" > ./outputs/temp/test_index.txt
echo "✅ Indices have been reset"

# ✅ Notify vLLM Servers to reset indices
echo ""
echo "🔄 Notifying vLLM Servers to reset indices..."
for port in "${USER_SIM_PORTS[@]}"; do
    curl -X POST "http://localhost:${port}/reset_index" \
        -H "Content-Type: application/json" \
        -d '{"train": true, "test": true}' 2>/dev/null || echo "⚠️  Cannot connect to vLLM Server on port $port"
done

echo ""
echo "🎓 Starting Chatbot training..."
LOG_FILE="./outputs/logs/chatbot_train_step${step}.log"
mkdir -p ./outputs/logs


PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
    data.train_files=$TRAIN_DATA \
    data.val_files=$VAL_DATA \
    data.train_batch_size=$TRAIN_BATCH_SIZE \
    data.val_batch_size=$VAL_BATCH_SIZE \
    data.max_prompt_length=8192 \
    data.max_response_length=500 \
    data.max_start_length=2048 \
    data.max_obs_length=500 \
    data.shuffle_train_dataloader=True \
    algorithm.adv_estimator=grpo \
    actor_rollout_ref.model.path=${chatbot_model_path} \
    actor_rollout_ref.model.enable_gradient_checkpointing=true \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.optim.lr_warmup_steps_ratio=0.1 \
    actor_rollout_ref.actor.use_kl_loss=true \
    actor_rollout_ref.actor.ppo_mini_batch_size=60 \
    actor_rollout_ref.actor.ppo_micro_batch_size=6 \
    actor_rollout_ref.actor.fsdp_config.param_offload=false \
    actor_rollout_ref.actor.fsdp_config.grad_offload=false \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=true \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=6 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.6 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=6 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    algorithm.no_think_rl=false \
    actor_rollout_ref.rollout.n_agent=8 \
    actor_rollout_ref.rollout.temperature=1.2 \
    actor_rollout_ref.actor.state_masking=true \
    trainer.logger=['console'] \
    +trainer.val_only=false \
    +trainer.val_before_train=false \
    trainer.default_hdfs_dir=null \
    trainer.n_gpus_per_node=$CHATBOT_N_GPUS \
    trainer.nnodes=1 \
    trainer.save_freq=5 \
    trainer.test_freq=$TEST_FREQ \
    trainer.project_name=$WAND_PROJECT \
    trainer.experiment_name=$EXPERIMENT_NAME \
    trainer.total_epochs=1 \
    trainer.total_training_steps=$training_steps \
    trainer.default_local_dir=./${STORAGE_PATH}/models/$model_name \
    "chat_server.url='$CHATBOT_URLS'" \
    chat_server.request_timeout_s=9999999 \
    chat_server.batch_size=30 \
    chat_server.use_mock=False \
    max_turns=12 \
    multi_turn_chat=True \
    actor_rollout_ref.rollout.dtype=bfloat16 \
    +generation_mode=call_chatbot \
    2>&1 | tee "$LOG_FILE"


TRAIN_EXIT_CODE=$?

# ✅ First close vLLM (if needed), then check training results
if [ "$keep_vllm_alive" = "false" ]; then
    echo ""
    echo "=========================================="
    echo "🧹 Training completed, shutting down vLLM Servers"
    echo "=========================================="

    pkill -9 -f "vllm_server" 2>/dev/null || true
    sleep 3

    REMAINING_PIDS=$(pgrep -f "vllm_server" || true)
    if [ -n "$REMAINING_PIDS" ]; then
        echo "⚠️ Warning: vLLM Server still running, force terminating..."
        kill -9 $REMAINING_PIDS 2>/dev/null || true
        sleep 2
    fi

    # Release ports
    for port in "${USER_SIM_PORTS[@]}"; do
        pid=$(lsof -ti:$port 2>/dev/null || true)
        if [ -n "$pid" ]; then
            echo "  Killing process on port $port: $pid"
            kill -9 $pid 2>/dev/null || true
        fi
    done

    rm -rf /tmp/ray_* 2>/dev/null || true
    rm -rf /dev/shm/ray_* 2>/dev/null || true

    echo "✅ vLLM Servers have been shut down, GPU ${USER_SIM_GPUS[0]} and ${USER_SIM_GPUS[1]} released"
    echo "=========================================="
else
    echo ""
    echo "=========================================="
    echo "✅ Training completed, keeping vLLM Servers running"
    echo "=========================================="
    echo "   vLLM Server 1 continues running on GPU ${USER_SIM_GPUS[0]} (port ${USER_SIM_PORTS[0]})"
    echo "   vLLM Server 2 continues running on GPU ${USER_SIM_GPUS[1]} (port ${USER_SIM_PORTS[1]})"
    echo "   Next iteration will reuse these services"
    echo "=========================================="
fi

# ✅ Check training results
if [ $TRAIN_EXIT_CODE -ne 0 ]; then
    echo ""
    echo "❌ Training failed! Exit code: $TRAIN_EXIT_CODE"
    echo "View log: $LOG_FILE"
    exit 1
fi

# ✅ Dynamically find latest checkpoint
echo ""
echo "🔍 Validating training results..."

MODEL_BASE_DIR="./outputs/models/${model_name}/actor"

if [ ! -d "$MODEL_BASE_DIR" ]; then
    echo "❌ Error: Model directory does not exist: $MODEL_BASE_DIR"
    echo ""
    echo "Possible reasons:"
    echo "  1. Error occurred during training"
    echo "  2. Model save path configuration error"
    echo "  3. Insufficient disk space"
    echo ""
    echo "Please check training log: $LOG_FILE"
    tail -50 "$LOG_FILE"
    exit 1
fi

# Find all checkpoints
CHECKPOINTS=$(ls -d ${MODEL_BASE_DIR}/global_step_* 2>/dev/null | sort -V)

if [ -z "$CHECKPOINTS" ]; then
    echo "❌ Error: No checkpoints found"
    echo ""
    echo "Directory contents:"
    ls -la "$MODEL_BASE_DIR"
    echo ""
    echo "Please check training log: $LOG_FILE"
    tail -50 "$LOG_FILE"
    exit 1
fi

# Get the latest checkpoint
LATEST_CHECKPOINT=$(echo "$CHECKPOINTS" | tail -1)
CHECKPOINT_STEP=$(basename "$LATEST_CHECKPOINT" | sed 's/global_step_//')

echo "✅ Found checkpoints:"
echo "$CHECKPOINTS" | while read ckpt; do
    echo "   - $(basename $ckpt)"
done
echo ""
echo "✅ Latest checkpoint: global_step_${CHECKPOINT_STEP}"

echo ""
echo "✅ Training completed!"
echo "   Model saved at: $LATEST_CHECKPOINT"
echo "   Log file: $LOG_FILE"
echo ""
